202105
chengshiwen/influx-proxy pull request #12
Opened 2021-05-28 09:39 UTC by shi0730

解决数据库名称加在表名前的情况
添加对保存策略操作的支持

2021-05-28 13:24 UTC, chengshiwen requested changes
特别棒的贡献👍
如果能将中文注释换成英文则会更好😃

2021-05-28 13:24 UTC, chengshiwen commented on backend/influxql.go
> +	return GetIdentifierFromTokens(tokens, []string{"on", "database", "from"}, getDatabase)
什么情况下会出现 数据库名称加在表名前的情况 呢

2021-05-31 00:55 UTC, shi0730 commented on backend/influxql.go
> +	return GetIdentifierFromTokens(tokens, []string{"on", "database", "from"}, getDatabase)
influxdb支持直接把数据库名加载表名前的查询.例如:SELECT mean("io_time") AS "mean_io_time" FROM "telegraf"."autogen"."diskio"

2021-06-02 03:14 UTC, chengshiwen commented on backend/influxql.go
> +	return GetIdentifierFromTokens(tokens, []string{"on", "database", "from"}, getDatabase)
因为 from 的特殊性，后面可能是完整的 `db.rp.meas` 或 `db..meas`的格式，也可能是单独 `meas`，所以为了确保这个修改足够覆盖所有的场景，可以增加下单元测试: https://github.com/chengshiwen/influx-proxy/blob/dev/backend/influxql_test.go

2021-06-15 08:00 UTC, merged